### DISCUSSION TITLE
Release v0.0.29

### DISCUSSION THREAD

**Discussion by shivasurya** [shivasurya/code-pathfinder#160] [Announcements]
This release has exciting new features such as `CI` command to scan source code for vulnerabilities within CI/CD ♾️  pipeline, docker support, GitHub Action support. 🎉 

## What's New?

1. Code-Pathfinder is now available in docker hub. Give it a try by pulling `shivasurya/code-pathfinder:stable-latest` 🐳 
2. [GitHub Action](https://github.com/shivasurya/code-pathfinder/blob/main/action.yml) is now supported and you can start scanning source code. 🎉 

```yaml
# add as step to github action yaml file
    - name: Code-Pathfinder SAST Scan
            uses: shivasurya/code-pathfinder@main
            with:
              command: 'ci'
              project: '.'
              output-file: 'output.json'
              output: 'json'
              ruleset: 'cpf/java'
```
3. Code-Pathfinder now supports CI command to scan for vulnerabilities in source code. ♾️ 

```bash
$ pathfinder ci --project /src/code-pathfinder/test-src --ruleset cpf/java --output json --output-file output.json
...
Executing in CI mode ♾️ 
```
Checkout Code-pathfinder rules registry [here](https://github.com/shivasurya/code-pathfinder/tree/main/pathfinder-rules)

![MS Dhoni Tenor (1)](https://github.com/user-attachments/assets/33d03736-04bd-4a91-a0ca-818c95beb3da)

## What's Changed
* Bump the npm_and_yarn group across 1 directory with 2 updates by @dependabot in https://github.com/shivasurya/code-pathfinder/pull/151
* feature: Implement CI based pathfinder scan - part 1 by @shivasurya in https://github.com/shivasurya/code-pathfinder/pull/153
* feature: Implement CI scan using pathfinder rules by @shivasurya in https://github.com/shivasurya/code-pathfinder/pull/155
* Bump astro from 4.15.12 to 4.16.3 in /docs in the npm_and_yarn group across 1 directory by @dependabot in https://github.com/shivasurya/code-pathfinder/pull/157
* ✨ Add GitHub Action template with action.yml by @shivasurya in https://github.com/shivasurya/code-pathfinder/pull/156
* fixed docker :whale: tag mistake by @shivasurya in https://github.com/shivasurya/code-pathfinder/pull/158
* release: Bump/v0.0.29 by @shivasurya in https://github.com/shivasurya/code-pathfinder/pull/159

**Full Changelog**: https://github.com/shivasurya/code-pathfinder/compare/v0.0.28...v0.0.29

<hr /><em>This discussion was created from the release <a href='https://github.com/shivasurya/code-pathfinder/releases/tag/v0.0.29'>Release v0.0.29</a>.</em>
